[package]
name = "edge-node"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { workspace = true }
reqwest = { workspace = true }
bytes = { workspace = true }
axum = { workspace = true }
futures-util = { workspace = true }
telemetry = { path = "../telemetry" }
cache = { path = "../cache" }
serde = { workspace = true }
serde_json = { workspace = true }
