global:
  scrape_interval: 2s

scrape_configs:
  - job_name: skynet-edge
    metrics_path: /__metrics
    static_configs:
      - targets:
          - host.docker.internal:18081
          - host.docker.internal:18082
          - host.docker.internal:18083
